CREATE PROCEDURE [dbo].[uspGetForms]
@form_id [int]
AS
SELECT [form_id]  ,
[form_name]       ,[form_description]   ,[form_email]      ,[form_redirect]
      ,[form_success_message]
      ,[form_password]
      ,[form_unique_ip]
      ,[form_frame_height]
      ,[form_has_css]
      ,[form_captcha]
      ,[form_active]
      ,[form_review]
      ,[esl_from_name]
      ,[esl_from_email_address]
      ,[esl_subject]
      ,[esl_content]
      ,[esl_plain_text]
      ,[esr_from_name]
      ,[esr_from_email_address]
      ,[esr_subject]
      ,[esr_content]
      ,[esr_plain_text]
  FROM [fb_forms]
  where (form_id = @form_id )