/****** Object:  Table [dbo].[Cat]    Script Date: 07/09/2010 00:13:41 ******/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Cat]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Cat](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[orderid] [bigint] NOT NULL,
	[cname] [nvarchar](255)  NOT NULL,
	[pid] [bigint] NOT NULL,
	[height] [int] NOT NULL,
	[sortid] [nvarchar](max) NOT NULL,
	[type] [smallint] NOT NULL,
	[type_content] [nvarchar](50)  NOT NULL,
	[id_content] [int] NULL,
	[id_setting_image_standard] [int] NULL,
	[lang] [int] NULL,
	[Delete_possible_self] [bit] NULL,
	[Delete_possible_subset_file] [bit] NULL,
	[Delete_possible_subset_folder] [bit] NULL,
	[insert_possible_subset_file] [bit] NULL,
	[insert_possible_subset_folder] [bit] NULL,
	[rename_possible_subset_file] [bit] NULL,
	[rename_possible_subset_folder] [bit] NULL,
 CONSTRAINT [PK_cat] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)
END

GO
if NOT Exists(select * from sys.columns where Name = N'insertUserId'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [insertUserId] int NULL
end 
GO
if NOT Exists(select * from sys.columns where Name = N'Valid'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [Valid] bit NULL
end 
GO
if NOT Exists(select * from sys.columns where Name = N'important'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [important] bit NULL
end 
GO
if NOT Exists(select * from sys.columns where Name = N'visitCounter'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [visitCounter] int NULL
end 
GO
UPDATE cat  SET visitCounter = 0  where visitCounter is null
GO
if NOT Exists(select * from sys.columns where Name = N'showTime'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [showTime] datetime NULL
end 
GO

if NOT Exists(select * from sys.columns where Name = N'deleted'  and Object_ID = Object_ID(N'cat')) 
begin  
 -- Column Exists 
 ALTER TABLE cat ADD [deleted] bit NULL
end 
GO
UPDATE    Cat   SET              deleted = 0   WHERE     (deleted IS NULL)
GO
UPDATE    Cat   SET              Valid = 0  WHERE     (Valid IS NULL)
GO
UPDATE  cat SET              showTime = CONVERT(DATETIME, '2012-12-12 00:00:00', 102)  WHERE     (showTime IS NULL)
GO

SET IDENTITY_INSERT [dbo].[Cat] ON
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (1, 1, N'ECM', 0, 1, N'#.1', 1, N'ECM            ', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (2, 1, N'محصولات', 1, 2, N'#.1.1', 1, N'shop', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (3, 1, N'فارسی', 2, 3, N'#.1.1.1', 1, N'shop', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (4, 2, N'English', 2, 3, N'#.1.1.2', 1, N'shop', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (6, 1, N'مقالات', 1, 2, N'#.1.2', 1, N'article', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (7, 1, N'فارسی', 6, 3, N'#.1.2.1', 1, N'article', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (8, 2, N'English', 6, 3, N'#.1.2.2', 1, N'article', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (9, 1, N'اخبار', 1, 2, N'#.1.3', 1, N'news', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (10, 1, N'فارسی', 9, 3, N'#.1.3.1', 1, N'news', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (11, 2, N'English', 9, 3, N'#.1.3.2', 1, N'news', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (33, 1, N'صفحات سفارشی', 1, 2, N'#.1.4', 1, N'special_pages', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (34, 1, N'فارسی', 33, 3, N'#.1.4.1', 1, N'special_pages', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (35, 2, N'English', 33, 3, N'#.1.4.2', 1, N'special_pages', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (39, 1, N'کتابخانه', 1, 2, N'#.1.5', 1, N'library', NULL, 13, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (40, 1, N'فارسی', 39, 3, N'#.1.5.1', 1, N'library', NULL, 13, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (41, 2, N'English', 39, 3, N'#.1.5.2', 1, N'library', NULL, 13, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (44, 1, N'نرم افزار', 1, 2, N'#.1.6', 1, N'software', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (45, 1, N'فارسی', 44, 3, N'#.1.6.1', 1, N'software', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (46, 2, N'English', 44, 3, N'#.1.6.2', 1, N'software', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (52, 1, N'عناوین ویژه', 1, 2, N'#.1.7', 1, N'special_items', NULL, 3, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (53, 1, N'فارسی', 52, 3, N'#.1.7.1', 1, N'special_items', NULL, 3, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (54, 2, N'English', 52, 3, N'#.1.7.2', 1, N'special_items', NULL, 3, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (58, 1, N'تصاویر', 1, 2, N'#.1.8', 1, N'picture', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (59, 1, N'فارسی', 58, 3, N'#.1.8.1', 1, N'picture', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (60, 1, N'English', 58, 3, N'#.1.8.2', 1, N'picture', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (61, 1, N'منو ها', 1, 2, N'#.1.9', 1, N'menu', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (62, 1, N'فارسی', 61, 3, N'#.1.9.1', 1, N'menu', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (63, 1, N'English', 61, 3, N'#.1.9.2', 1, N'menu', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (118, 1, N'منوی اصلی', 62, 4, N'#.1.9.1.1', 1, N'menu', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (253, 1, N'صفحه اصلی', 53, 4, N'#.1.7.1.1', 1, N'special_items', NULL, 3, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (254, 1, N'Home Page', 54, 4, N'#.1.7.2.1', 1, N'special_items', NULL, 3, NULL, 1, 1, 0, 1, 0, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (336, 1, N'پیوند ها', 1, 2, N'#.1.A10', 1, N'Link', NULL, 1, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (339, 1, N'فارسی', 336, 3, N'#.1.A10.1', 1, N'Link', NULL, 1, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (342, 1, N'English', 336, 3, N'#.1.A10.2', 1, N'Link', NULL, 1, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (346, 1, N'خدمات', 1, 2, N'#.1.A11', 1, N'service', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (349, 1, N'فارسی', 346, 3, N'#.1.A11.1', 1, N'service', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (352, 1, N'English', 346, 3, N'#.1.A11.2', 1, N'service', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (354, 1, N'موبایل', 1, 2, N'#.1.A12', 1, N'mobile', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (357, 1, N'فارسی', 354, 3, N'#.1.A12.1', 1, N'mobile', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (358, 1, N'English', 354, 3, N'#.1.A12.2', 1, N'mobile', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (360, 1, N'خودرو', 1, 2, N'#.1.A13', 1, N'car', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (361, 1, N'فارسی', 360, 3, N'#.1.A13.1', 1, N'car', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (364, 1, N'English', 360, 3, N'#.1.A13.2', 1, N'car', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (365, 1, N'راهنما', 1, 2, N'#.1.A14', 1, N'help', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (366, 1, N'فارسی', 365, 3, N'#.1.A14.1', 1, N'help', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (367, 1, N'English', 365, 3, N'#.1.A14.2', 1, N'help', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (368, 1, N'تمپلیت', 1, 2, N'#.1.A15', 1, N'template', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (369, 1, N'فارسی', 368, 3, N'#.1.A15.1', 1, N'template', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (370, 1, N'English', 368, 3, N'#.1.A15.2', 1, N'template', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (371, 1, N'کلیپ', 1, 2, N'#.1.A16', 1, N'clip', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (374, 1, N'فارسی', 371, 3, N'#.1.A16.1', 1, N'clip', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (376, 1, N'English', 371, 3, N'#.1.A16.2', 1, N'clip', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (378, 1, N'نام دامنه', 1, 2, N'#.1.A17', 1, N'domain', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (379, 1, N'فارسی', 378, 3, N'#.1.A17.1', 1, N'domain', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (381, 1, N'English', 378, 3, N'#.1.A17.2', 1, N'domain', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (383, 1, N'پرتال', 1, 2, N'#.1.A18', 1, N'portal', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (384, 1, N'فارسی', 383, 3, N'#.1.A18.1', 1, N'portal', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (385, 1, N'English', 383, 3, N'#.1.A18.2', 1, N'portal', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (386, 1, N'اسکریپت', 1, 2, N'#.1.A19', 1, N'script', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (387, 1, N'فارسی', 386, 3, N'#.1.A19.1', 1, N'script', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (388, 1, N'English', 386, 3, N'#.1.A19.2', 1, N'script', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (1984, 1, N'پروژه های پژوهشی', 1, 2, N'#.1.A20', 1, N'research_project', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (1987, 1, N'فارسی', 1984, 3, N'#.1.A20.1', 1, N'research_project', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (1988, 1, N'English', 1984, 3, N'#.1.A20.2', 1, N'research_project', NULL, NULL, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (2036, 2, N'منوی چرخشی', 62, 4, N'#.1.9.1.2', 1, N'menu', NULL, 1, NULL, 1, 1, 1, 1, 1, 1, 1)
INSERT [dbo].[Cat] ([id], [orderid], [cname], [pid], [height], [sortid], [type], [type_content], [id_content], [id_setting_image_standard], [lang], [Delete_possible_self], [Delete_possible_subset_file], [Delete_possible_subset_folder], [insert_possible_subset_file], [insert_possible_subset_folder], [rename_possible_subset_file], [rename_possible_subset_folder]) VALUES (2068, 1, N'zxxzxz', 1987, 4, N'#.1.A20.1.1', 2, N'research_project', 1, 1, NULL, 1, 1, 1, 1, 1, 1, 1)
SET IDENTITY_INSERT [dbo].[Cat] OFF
GO

