CREATE TABLE [dbo].[core_currency](
	[currency_id] [int]  NOT NULL,
	[currency_title] [nvarchar](50) NULL,
	[currency_code] [varchar](4) NULL,
	[dictionary_id] [int] NULL,
 CONSTRAINT [PK_core_currency] PRIMARY KEY CLUSTERED 
(
	[currency_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (1,'AFN', N'Afghan Afghani',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (2,'ALL', N'Albanian Lek',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (3,'DZD', N'Algerian Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (4,'ADF', N'Andorran Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (5,'ADP', N'Andorran Peseta',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (6,'AOA', N'Angolan Kwanza',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (7,'ARS', N'Argentine Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (8,'AMD', N'Armenian Dram',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (9,'AWG', N'Aruban Florin',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (10,'AUD', N'Australian Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (11,'AZN', N'Azerbaijan New Manat',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (12,'BSD', N'Bahamian Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (13,'BHD', N'Bahraini Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (14,'BDT', N'Bangladeshi Taka',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (15,'BBD', N'Barbados Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (16,'BYR', N'Belarusian Ruble',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (17,'BZD', N'Belize Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (18,'BMD', N'Bermudian Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (19,'BTN', N'Bhutan Ngultrum',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (20,'BOB', N'Bolivian Boliviano',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (21,'BAM', N'Bosnian Mark',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (22,'BWP', N'Botswana Pula',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (23,'BRL', N'Brazilian Real',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (24,'BND', N'Brunei Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (25,'BGN', N'Bulgarian Lev',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (26,'BIF', N'Burundi Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (27,'XOF', N'CFA Franc BCEAO',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (28,'XAF', N'CFA Franc BEAC',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (29,'CAD', N'Canadian Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (30,'CVE', N'Cape Verde Escudo',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (31,'KYD', N'Cayman Islands Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (32,'CLP', N'Chilean Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (33,'COP', N'Colombian Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (34,'KMF', N'Comoros Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (35,'CDF', N'Congolese Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (36,'CRC', N'Costa Rican Colon',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (37,'HRK', N'Croatian Kuna',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (38,'CUC', N'Cuban Convertible Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (39,'CUP', N'Cuban Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (40,'CZK', N'Czech Koruna',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (41,'CSK', N'Czechoslovakian Koruna',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (42,'DKK', N'Danish Krone',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (43,'DJF', N'Djibouti Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (44,'DOP', N'Dominican Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (45,'XCD', N'East Carribean Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (46,'ECS', N'Ecuador Sucre',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (47,'EGP', N'Egyptian Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (48,'SVC', N'El Salvador Colon',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (49,'EEK', N'Estonian Kroon',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (50,'ETB', N'Ethiopian Birr',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (51,'EUR', N'Euro',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (52,'FKP', N'Falkland Islands Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (53,'FJD', N'Fiji Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (54,'GMD', N'Gambian Dalasi',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (55,'GEL', N'Georgian Lari',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (56,'GHS', N'Ghanaian New Cedi',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (57,'GIP', N'Gibraltar Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (58,'GTQ', N'Guatemalan Quetzal',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (59,'GNF', N'Guinea Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (60,'GYD', N'Guyanan Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (61,'HTG', N'Haitian Gourde',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (62,'HNL', N'Honduran Lempira',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (63,'HKD', N'Hong Kong Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (64,'HUF', N'Hungarian Forint',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (65,'ISK', N'Iceland Krona',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (66,'INR', N'Indian Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (67,'IDR', N'Indonesian Rupiah',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (68,'IRR', N'Iranian Rial',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (69,'IQD', N'Iraqi Dinar',412)
/*INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (70,'ILS', N'Israeli New Shekel',412)*/
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (71,'JMD', N'Jamaican Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (72,'JPY', N'Japanese Yen',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (73,'JOD', N'Jordanian Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (74,'KHR', N'Kampuchean Riel',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (75,'KZT', N'Kazakhstan Tenge',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (76,'KES', N'Kenyan Shilling',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (77,'KRW', N'Korean Won',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (78,'KWD', N'Kuwaiti Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (79,'KGS', N'Kyrgyzstanian Som',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (80,'LAK', N'Lao Kip',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (81,'LVL', N'Latvian Lats',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (82,'LBP', N'Lebanese Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (83,'LSL', N'Lesotho Loti',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (84,'LRD', N'Liberian Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (85,'LYD', N'Libyan Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (86,'LTL', N'Lithuanian Litas',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (87,'MOP', N'Macau Pataca',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (87,'MKD', N'Macedonian Denar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (89,'MGA', N'Malagasy Ariary',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (90,'MWK', N'Malawi Kwacha',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (91,'MYR', N'Malaysian Ringgit',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (92,'MVR', N'Maldive Rufiyaa',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (93,'MRO', N'Mauritanian Ouguiya',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (94,'MUR', N'Mauritius Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (95,'MXN', N'Mexican Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (96,'MDL', N'Moldovan Leu',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (97,'MNT', N'Mongolian Tugrik',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (98,'MAD', N'Moroccan Dirham',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (99,'MZN', N'Mozambique New Metical',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (100,'MMK', N'Myanmar Kyat',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (101,'ANG', N'NL Antillian Guilder',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (102,'NAD', N'Namibia Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (103,'NPR', N'Nepalese Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (104,'NZD', N'New Zealand Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (105,'NIO', N'Nicaraguan Cordoba Oro',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (106,'NGN', N'Nigerian Naira',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (107,'KPW', N'North Korean Won',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (108,'NOK', N'Norwegian Kroner',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (109,'OMR', N'Omani Rial',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (110,'PKR', N'Pakistan Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (111,'PAB', N'Panamanian Balboa',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (112,'PGK', N'Papua New Guinea Kina',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (113,'PYG', N'Paraguay Guarani',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (114,'PEN', N'Peruvian Nuevo Sol',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (115,'PHP', N'Philippine Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (116,'PLN', N'Polish Zloty',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (117,'QAR', N'Qatari Rial',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (118,'RON', N'Romanian New Leu',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (119,'RUB', N'Russian Rouble',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (120,'RWF', N'Rwandan Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (121,'WST', N'Samoan Tala',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (122,'STD', N'Sao Tome/Principe Dobra',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (123,'SAR', N'Saudi Riyal',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (124,'RSD', N'Serbian Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (125,'SCR', N'Seychelles Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (126,'SLL', N'Sierra Leone Leone',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (127,'SGD', N'Singapore Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (128,'SBD', N'Solomon Islands Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (129,'SOS', N'Somali Shilling',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (130,'ZAR', N'South African Rand',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (131,'LKR', N'Sri Lanka Rupee',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (132,'SHP', N'St. Helena Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (133,'SDG', N'Sudanese Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (134,'SRD', N'Suriname Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (135,'SZL', N'Swaziland Lilangeni',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (136,'SEK', N'Swedish Krona',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (137,'CHF', N'Swiss Franc',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (138,'SYP', N'Syrian Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (139,'TWD', N'Taiwan Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (140,'TZS', N'Tanzanian Shilling',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (141,'THB', N'Thai Baht',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (142,'TOP', N'Tongan Pa anga',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (143,'TTD', N'Trinidad/Tobago Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (144,'TND', N'Tunisian Dinar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (145,'TMT', N'Turkmenistan New Manats',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (146,'USD', N'US Dollar',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (147,'UGS', N'Uganda Shilling',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (148,'UAH', N'Ukraine Hryvnia',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (149,'GBP', N'United Kingdom Pound',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (150,'UYU', N'Uruguayan Peso',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (151,'AED', N'Utd. Arab Emir. Dirham',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (152,'VUV', N'Vanuatu Vatu',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (153,'VEF', N'Venezuelan Bolivar Fuerte',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (154,'VND', N'Vietnamese Dong',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (155,'YER', N'Yemen Rial',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (156,'TRY', N'Yeni Turk Lirasi',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (157,'ZMK', N'Zambian Kwacha',412)
INSERT [dbo].[core_currency] ([currency_id], [currency_code],[currency_title],[dictionary_id]) VALUES (158,'ZWD', N'Zimbabwe Dollar',412)