IF NOT EXISTS
( 

SELECT [name] 
    FROM sys.tables where [name] = N'core_country'


)
CREATE TABLE [dbo].[core_country](
	[country_id] [int] NOT NULL,
	[country_title] [nvarchar](50) NULL,
	[country_code] [varchar](4) NULL,
	[dictionary_id] [int] NULL,
 CONSTRAINT [PK_core_country] PRIMARY KEY CLUSTERED 
(
	[country_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (0,'00', N'All Country',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'AX', N'Åland Islands',412)
/*INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (2,'AF', N'Afghanistan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (3,'AL', N'Albania',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (4,'DZ', N'Algeria',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (5,'AS', N'American Samoa',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (6,'AD', N'Andorra',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (7,'AO', N'Angola',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (8,'AI', N'Anguilla',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (9,'AQ', N'Antarctica',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (10,'AG', N'Antigua And Barbuda',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (11,'AR', N'Argentina',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (12,'AM', N'Armenia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (13,'AW', N'Aruba',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (14,'AU', N'Australia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (15,'AT', N'Austria',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (16,'AZ', N'Azerbaijan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (17,'BS', N'Bahamas',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (18,'BH', N'Bahrain',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (19,'BD', N'Bangladesh',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (20,'BB', N'Barbados',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (21,'BY', N'Belarus',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (22,'BE', N'Belgium',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (23,'BZ', N'Belize',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (24,'BJ', N'Benin',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (25,'BM', N'Bermuda',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (26,'BT', N'Bhutan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (27,'BO', N'Bolivia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (28,'BA', N'Bosnia and Herzegovina',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (29,'BW', N'Botswana',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (30,'BV', N'Bouvet Island',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (31,'BR', N'Brazil',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (32,'IO', N'British Indian Ocean Territory',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (33,'BN', N'Brunei',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (34,'BG', N'Bulgaria',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (35,'BF', N'Burkina Faso',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (36,'BI', N'Burundi',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (37,'KH', N'Cambodia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (38,'CM', N'Cameroon',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (39,'CA', N'Canada',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (40,'CV', N'Cape Verde',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (41,'KY', N'Cayman Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (42,'CF', N'Central African Republic',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (43,'TD', N'Chad',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (44,'CL', N'Chile',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (45,'CN', N'China',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (46,'CX', N'Christmas Island',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (47,'CC', N'Cocos (Keeling) Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (48,'CO', N'Colombia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (49,'KM', N'Comoros',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (50,'CG', N'Congo',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (51,'CD', N'Congo, Democractic Republic',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (52,'CK', N'Cook Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (53,'CR', N'Costa Rica',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (54,'CI', N'Cote D Ivoire (Ivory Coast)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (55,'HR', N'Croatia (Hrvatska)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (56,'CU', N'Cuba',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (57,'CY', N'Cyprus',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (58,'CZ', N'Czech Republic',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (59,'DK', N'Denmark',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (60,'DJ', N'Djibouti',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (61,'DM', N'Dominica',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (62,'DO', N'Dominican Republic',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (63,'TP', N'East Timor',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (64,'EC', N'Ecuador',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (65,'EG', N'Egypt',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (66,'SV', N'El Salvador',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (67,'GQ', N'Equatorial Guinea',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (68,'ER', N'Eritrea',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (69,'8EE', N'Estonia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (70,'ET', N'Ethiopia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (71,'FK', N'Falkland Islands (Islas Malvinas)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (72,'FO', N'Faroe Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (73,'FJ', N'Fiji Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (74,'FI', N'Finland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (77,'FR', N'France',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (78,'FX', N'France, Metropolitan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (79,'GF', N'French Guiana',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (80,'PF', N'French Polynesia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (81,'TF', N'French Southern Territories',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (82,'GA', N'Gabon',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (83,'GM', N'Gambia, The',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (84,'GE', N'Georgia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (85,'DE', N'Germany',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (86,'GH', N'Ghana',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GI', N'Gibraltar',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GR', N'Greece',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GL', N'Greenland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GD', N'Grenada',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GP', N'Guadeloupe',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GU', N'Guam',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GT', N'Guatemala',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GG', N'Guernsey',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GN', N'Guinea',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GW', N'Guinea-Bissau',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GY', N'Guyana',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'HT', N'Haiti',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'HM', N'Heard and McDonald Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'HN', N'Honduras',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'HK', N'Hong Kong S.A.R.',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'HU', N'Hungary',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IS', N'Iceland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IN', N'India',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ID', N'Indonesia',412)*/
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (104,'IR', N'Iran',413)
/*
 INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IQ', N'Iraq',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IE', N'Ireland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IM', N'Isle of Man',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IL', N'Israel',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'IT', N'Italy',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'JM', N'Jamaica',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'JP', N'Japan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'JE', N'Jersey',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'JO', N'Jordan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KZ', N'Kazakhstan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KE', N'Kenya',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KI', N'Kiribati',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KR', N'Korea',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KP', N'Korea, North',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KW', N'Kuwait',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KG', N'Kyrgyzstan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LA', N'Laos',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LV', N'Latvia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LB', N'Lebanon',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LS', N'Lesotho',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LR', N'Liberia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LY', N'Libya',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LI', N'Liechtenstein',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LT', N'Lithuania',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LU', N'Luxembourg',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MO', N'Macau S.A.R.',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MK', N'Macedonia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MG', N'Madagascar',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MW', N'Malawi',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MY', N'Malaysia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MV', N'Maldives',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ML', N'Mali',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MT', N'Malta',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MH', N'Marshall Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MQ', N'Martinique',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MR', N'Mauritania',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MU', N'Mauritius',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'YT', N'Mayotte',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MX', N'Mexico',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'FM', N'Micronesia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MD', N'Moldova',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MC', N'Monaco',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MN', N'Mongolia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ME', N'Montenegro',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MS', N'Montserrat',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MA', N'Morocco',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MZ', N'Mozambique',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MM', N'Myanmar',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NA', N'Namibia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NR', N'Nauru',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NP', N'Nepal',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NL', N'Netherlands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'AN', N'Netherlands Antilles',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NC', N'New Caledonia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NZ', N'New Zealand',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NI', N'Nicaragua',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NE', N'Niger',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NG', N'Nigeria',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NU', N'Niue',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NF', N'Norfolk Island',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'MP', N'Northern Mariana Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'NO', N'Norway',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'OM', N'Oman',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PK', N'Pakistan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PW', N'Palau',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PS', N'Palestinian Territory, Occupied',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PA', N'Panama',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PG', N'Papua new Guinea',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PY', N'Paraguay',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PE', N'Peru',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PH', N'Philippines',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PN', N'Pitcairn Island',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PL', N'Poland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PT', N'Portugal',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PR', N'Puerto Rico',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'QA', N'Qatar',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'RE', N'Reunion',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'RO', N'Romania',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'RU', N'Russia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'RW', N'Rwanda',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SH', N'Saint Helena',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'KN', N'Saint Kitts And Nevis',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LC', N'Saint Lucia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'PM', N'Saint Pierre and Miquelon',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VC', N'Saint Vincent And The Grenadines',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'WS', N'Samoa',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SM', N'San Marino',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ST', N'Sao Tome and Principe',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SA', N'Saudi Arabia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SN', N'Senegal',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'RS', N'Serbia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SC', N'Seychelles',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SL', N'Sierra Leone',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SG', N'Singapore',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SX', N'Sint Maarten',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SK', N'Slovakia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SI', N'Slovenia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SB', N'Solomon Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SO', N'Somalia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ZA', N'South Africa',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GS', N'South Georgia And The South Sandwich Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ES', N'Spain',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'LK', N'Sri Lanka',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SD', N'Sudan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SR', N'Suriname',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SJ', N'Svalbard And Jan Mayen Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SZ', N'Swaziland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SE', N'Sweden',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'CH', N'Switzerland',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'SY', N'Syria',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TW', N'Taiwan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TJ', N'Tajikistan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TZ', N'Tanzania',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TH', N'Thailand',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TL', N'Timor-Leste',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TG', N'Togo',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TK', N'Tokelau',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TO', N'Tonga',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TT', N'Trinidad And Tobago',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TN', N'Tunisia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TR', N'Turkey',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TM', N'Turkmenistan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TC', N'Turks And Caicos Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'TV', N'Tuvalu',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'UG', N'Uganda',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'UA', N'Ukraine',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'AE', N'United Arab Emirates',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'GB', N'United Kingdom',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'US', N'United States',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'UM', N'United States Minor Outlying Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'UY', N'Uruguay',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'UZ', N'Uzbekistan',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VU', N'Vanuatu',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VA', N'Vatican City State (Holy See)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VE', N'Venezuela',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VN', N'Vietnam',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VG', N'Virgin Islands (British)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'VI', N'Virgin Islands (US)',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'WF', N'Wallis And Futuna Islands',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'EH', N'WESTERN SAHARA',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'YE', N'Yemen',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ZM', N'Zambia',412)
INSERT [dbo].[core_country] ([country_id], [country_code],[country_title],[dictionary_id]) VALUES (1,'ZW', N'Zimbabwe',412)
*/